### ISSUE TITLE
Integrate Cloudinsight icons into PlantUML 

### ISSUE THREAD

**Issue by arnaudroques** [rabelenda/cicon-plantuml-sprites#1]
Many thanks for your contribution!
If you are ok with the idea, we would like to include your library into the standard distribution of PlantUML.
(so in https://github.com/plantuml/plantuml/tree/master/stdlib like we have done for https://github.com/milo-minderbinder/AWS-PlantUML/issues/20 )

That way, people would be able to use it out-of-the box with the following syntax:

```
@startuml
!include <sprite/tomcat>
!include <sprite/kafka>
!include <sprite/java>
!include <sprite/cassandra>

title Cloudinsight sprites example

skinparam monochrome true

rectangle "<$tomcat>\nwebapp" as webapp
queue "<$kafka>" as kafka
rectangle "<$java>\ndaemon" as daemon
database "<$cassandra>" as cassandra

webapp -> kafka
kafka -> daemon
daemon --> cassandra 

@enduml

```
Your repository would still be the official source for this library: we would just duplicate files into our repository.

What do you think about it ?

**Comment by rabelenda** [comment]
Sounds great to me! Just in case, ask cloud insight since I extracted the spirites from them and plantuml is a lot more popular than any of my personal repos :)

**Comment by rabelenda** [comment]
Any news on this? if you don't have any comments or further requests I would close this issue.

**Comment by arnaudroques** [comment]
No news yet, but you can close this issue on your side.
Thanks
