### ISSUE TITLE
Add Kotlin sprite

### ISSUE THREAD

**Issue by kollstrom** [rabelenda/cicon-plantuml-sprites#2]
It would be nice if we could add the Kotlin logo as part of this library.
Is the only thing needed a version of the Kotlin logo as a black and white png?
Any other requirements to be aware of?

**Comment by rabelenda** [comment]
In fact I created this repo from a script (included in the repo) to convert logos from a known source, to avoid having to invest time on converting, sizing, etc each logo manually. Check #4 for more details on potential solution to this request.

**Comment by rabelenda** [comment]
Hi, I created [this other repo](https://github.com/rabelenda/gilbarbara-plantuml-sprites/blob/master/README.md), I hope this helps.

**Comment by kollstrom** [comment]
Perfect, thanks!
