### ISSUE TITLE
Add Akka Sprite

### ISSUE THREAD

**Issue by moglideveloper** [rabelenda/cicon-plantuml-sprites#4]
It would be nice if we could add the Akka logo as part of this library.

**Comment by rabelenda** [comment]
Hi, I would like to have such logos to use them in plantuml, but the source of current sprites (https://github.com/cloudinsight/cicon) doesn't include such logos. I would need to create another script for extracting the logos from other sources, and then the repo should probably be renamed. Will see if have enough time to review other sources and how much time would take me to migrate/convert them.

Regards

**Comment by rabelenda** [comment]
Check #2 answer which includes a solution to this.
